#!/bin/bash

# Exit on error
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# ask and set settings
# (use "echo PURGE | sudo debconf-communicate oco-agent" to reset from /var/cache/debconf/config.dat)
db_input high oco-agent/server-name || true
db_go || true
db_get oco-agent/server-name
if [ "$RET" != "" ]; then
	RET="https://$RET/api-agent.php"
fi
sed -i "s|SERVERURL|$RET|g" /etc/oco-agent.ini

db_input high oco-agent/agent-key || true
db_go || true
db_get oco-agent/agent-key
sed -i "s|AGENTKEY|$RET|g" /etc/oco-agent.ini

db_input high oco-agent/server-key || true
db_go || true
db_get oco-agent/server-key
sed -i "s|SERVERKEY|$RET|g" /etc/oco-agent.ini

# register and start service
systemctl daemon-reload || true
systemctl enable oco-agent || true

if [ "$(systemctl is-active oco-agent || true)" == "inactive" ]; then
	systemctl start oco-agent || true
else
	echo "Service already running, no automatic restart is made in order to gracefully complete the OCO agent update software job"
fi
